#!/usr/bin/env bash
set -euo pipefail

export PROJ_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"

cd "${PROJ_HOME}/core"
rm -rf lib || true
mkdir -p lib
yarn run prepublish

cd "${PROJ_HOME}/web"
rm -rf node_modules/remacro || true
yarn install
